apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch-gpu-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pytorch-gpu-app
  template:
    metadata:
      labels:
        app: pytorch-gpu-app
    spec:
      containers:
      - name: pytorch-gpu-container
        image: gerardrecinto/pytorch-gpu:latest
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["python3", "train.py"]

